service: serverless-aws

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.users
    events:
      - http:
          path: /users
          method: get
